export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className="bg-gray-50 dark:bg-slate-900 text-slate-800 dark:text-slate-50">{children}</body>
    </html>
  )
}
